# Generated by Django 6.0.2 on 2026-02-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='code',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True),
        ),
    ]
