# Generated by Django 6.0.2 on 2026-03-06 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('can_access_accounting', models.BooleanField(default=False)),
                ('can_access_inventory', models.BooleanField(default=False)),
                ('can_access_sales', models.BooleanField(default=False)),
                ('can_access_purchases', models.BooleanField(default=False)),
                ('can_access_hr', models.BooleanField(default=False)),
                ('can_access_taxation', models.BooleanField(default=False)),
                ('can_manage_users', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.role'),
        ),
    ]
