# Generated by Django 6.0.2 on 2026-02-28 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='tds_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='tds_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
