# Generated by Django 6.0.2 on 2026-02-28 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_alter_voucher_number'),
        ('purchases', '0003_purchaseinvoice_tds_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='tax_amount',
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='tds_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type__in': ['Liability', 'Asset']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.ledger'),
        ),
    ]
