# Generated by Django 6.0.2 on 2026-02-28 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_alter_voucher_number'),
        ('purchases', '0004_remove_purchaseinvoice_tax_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='tds_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'name__icontains': 'TDS'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.ledger'),
        ),
    ]
