# Generated by Django 6.0.2 on 2026-03-01 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_remove_purchaseinvoice_tds_account_and_more'),
        ('taxation', '0004_remove_tdsjournalline_tds_sgi_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='tds_heading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxation.tdsheading'),
        ),
    ]
