# Generated by Django 6.0.2 on 2026-03-01 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_alter_voucher_number'),
        ('purchases', '0008_remove_purchaseinvoiceitem_tds_heading_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseinvoiceitem',
            name='tds_account',
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='tds_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'name__icontains': 'TDS'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.ledger'),
        ),
    ]
