# Generated by Django 6.0.2 on 2026-03-01 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_alter_voucher_number'),
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('date', models.DateField()),
                ('month', models.DateField(help_text='Reference month for payroll')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Finalized', 'Finalized')], default='Draft', max_length=20)),
                ('total_gross', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_tds', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_net', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('payment_ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_payments', to='accounting.ledger')),
                ('salary_expense_ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_expenses', to='accounting.ledger')),
                ('tds_payable_ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_tds', to='accounting.ledger')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tds_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tds_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_payable', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.employee')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='hr.payrollrun')),
            ],
        ),
    ]
