# Generated by Django 6.0.2 on 2026-03-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_employee_basic_salary_payrollrun_payrollentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payrollentry',
            old_name='tds_amount',
            new_name='it_amount',
        ),
        migrations.RemoveField(
            model_name='payrollentry',
            name='tds_rate',
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='it_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='IT % (Income Tax / Other TDS)', max_digits=5),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='sst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='sst_rate',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='SST % (Social Security Tax, e.g. 1%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='total_tds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='calendar_type',
            field=models.CharField(choices=[('AD', 'English (AD)'), ('BS', 'Nepali (BS)')], default='AD', max_length=5),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='total_it',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Income Tax'),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='total_sst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Social Security Tax (1%)'),
        ),
    ]
