# Generated by Django 6.0.2 on 2026-02-26 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('valuation_method', models.CharField(choices=[('FIFO', 'FIFO'), ('Weighted Average', 'Weighted Average')], default='FIFO', max_length=20)),
                ('sales_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_stock', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('is_taxable', models.BooleanField(default=True)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=13.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='UnitOfMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('adjustment_type', models.CharField(choices=[('Addition', 'Addition'), ('Reduction', 'Reduction'), ('Breakage', 'Breakage')], max_length=20)),
                ('reason', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
            ],
        ),
    ]
