# Generated by Django 6.0.2 on 2026-02-28 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_alter_voucher_number'),
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cogs_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 'Expense'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cogs_items', to='accounting.ledger'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('Goods', 'Goods / Physical Product'), ('Service', 'Service')], default='Goods', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='purchase_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 'Expense'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_items', to='accounting.ledger'),
        ),
        migrations.AddField(
            model_name='item',
            name='sales_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 'Income'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_items', to='accounting.ledger'),
        ),
    ]
