# Generated by Django 6.0.2 on 2026-03-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_item_cogs_account_item_item_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='barcode',
            field=models.CharField(blank=True, help_text='Specific Barcode (EAN, UPC, etc.) - Falls back to SKU if empty', max_length=100, null=True),
        ),
    ]
