# Generated by Django 6.0.2 on 2026-02-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_vat_registered',
            field=models.BooleanField(default=True, verbose_name='VAT Registered'),
        ),
        migrations.AddField(
            model_name='client',
            name='uses_inventory',
            field=models.BooleanField(default=True, verbose_name='Uses Inventory Module'),
        ),
    ]
