# Generated by Django 6.0.2 on 2026-03-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_client_is_vat_registered_client_uses_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='default_vat_rate',
            field=models.DecimalField(decimal_places=2, default=13.0, max_digits=5, verbose_name='Default VAT Rate (%)'),
        ),
    ]
