# Generated by Django 6.0.2 on 2026-03-07 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_tenantrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='pan_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='PAN/VAT Number'),
        ),
        migrations.AddField(
            model_name='tenantrequest',
            name='pan_number',
            field=models.CharField(default='', max_length=20, verbose_name='PAN Number'),
        ),
    ]
