# Generated by Django 6.0.2 on 2026-03-01 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0007_alter_voucher_number'),
        ('contacts', '0002_contact_code'),
        ('hr', '0003_rename_tds_amount_payrollentry_it_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TDSHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='IRD Code e.g. 11112', max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TDSJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voucher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tds_journal', to='accounting.voucher')),
            ],
        ),
        migrations.CreateModel(
            name='TDSJournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subledger_type', models.CharField(choices=[('None', 'None'), ('Employee', 'Employee'), ('Contact', 'Contact')], default='None', max_length=20)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tds_sgi_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='TDS SGI Code')),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.contact')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.employee')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.ledger')),
                ('tds_heading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxation.tdsheading')),
                ('tds_journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tds_lines', to='taxation.tdsjournal')),
            ],
        ),
    ]
