# Generated by Django 6.0.2 on 2026-03-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tdsheading',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
