# Generated by Django 6.0.2 on 2026-03-01 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxation', '0002_tdsheading_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdsjournalline',
            name='tds_heading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tds_lines', to='taxation.tdsheading'),
        ),
    ]
