# Generated by Django 6.0.2 on 2026-03-01 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_alter_voucher_number'),
        ('taxation', '0003_alter_tdsjournalline_tds_heading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tdsjournalline',
            name='tds_sgi_code',
        ),
        migrations.AddField(
            model_name='tdsjournalline',
            name='taxable_ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taxed_lines', to='accounting.ledger'),
        ),
    ]
