# Generated by Django 6.0.2 on 2026-02-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountgroup',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='ledger',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
