# Generated by Django 6.0.2 on 2026-02-27 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_accountgroup_code_ledger_code'),
        ('contacts', '0002_contact_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherentry',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.contact'),
        ),
    ]
