# Generated by Django 6.0.2 on 2026-02-28 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_voucherentry_contact'),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherentry',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.employee'),
        ),
    ]
