# Generated by Django 6.0.2 on 2026-02-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_voucherentry_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='subledger_type',
            field=models.CharField(choices=[('None', 'None'), ('Contact', 'Contact'), ('Employee', 'Employee')], default='None', max_length=20),
        ),
    ]
