# Generated by Django 6.0.2 on 2026-02-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_ledger_subledger_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
