# Generated by Django 6.0.2 on 2026-02-28 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_alter_voucher_number'),
        ('sales', '0002_invoice_tds_amount_invoice_tds_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tds_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'name__icontains': 'TDS'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.ledger'),
        ),
    ]
