# Generated by Django 6.0.2 on 2026-02-28 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_invoice_tds_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='tds_account',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tds_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tds_rate',
        ),
    ]
