# Generated by Django 6.0.2 on 2026-02-28 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_alter_voucher_number'),
        ('sales', '0004_remove_invoice_tds_account_remove_invoice_tds_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='tds_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'name__icontains': 'TDS'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.ledger'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='tds_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='tds_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
