# Generated by Django 6.0.2 on 2026-02-28 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_invoiceitem_tds_account_invoiceitem_tds_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='tds_account',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='tds_amount',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='tds_rate',
        ),
    ]
