# Generated by Django 6.0.2 on 2026-03-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_remove_invoiceitem_tds_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount_type',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('percent', 'Percent')], default='fixed', max_length=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
